# Generated by Django 5.2.7 on 2025-11-03 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_inicio', models.DateField()),
                ('total_sesiones', models.IntegerField(default=24)),
                ('sesiones_completadas', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'Agenda de Estudiante',
                'verbose_name_plural': 'Agendas de Estudiantes',
                'ordering': ['estudiante__apellido_paterno'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('estado', models.CharField(choices=[('programada', '🟡 Programada'), ('asistio', '🟢 Asistió'), ('ausente', '🔴 Ausente'), ('justificada', '🟠 Justificada')], default='programada', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='agenda.agendaestudiante')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'ordering': ['fecha_programada'],
                'unique_together': {('agenda', 'fecha_programada')},
            },
        ),
    ]
