# Generated by Django 5.2.7 on 2025-11-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='progreso',
            field=models.IntegerField(blank=True, help_text='Calificación del progreso en la sesión (1-10)', null=True, verbose_name='Progreso (1-10)'),
        ),
    ]
