# Generated by Django 5.2.7 on 2025-11-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_sesion_progreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='justificacion',
            field=models.TextField(blank=True, help_text='Descripción del motivo de la justificación (solo para ausencias justificadas)', null=True, verbose_name='Motivo de Justificación'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Notas y observaciones generales del desempeño del estudiante', null=True, verbose_name='Observaciones de la Sesión'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='progreso',
            field=models.IntegerField(blank=True, help_text='Calificación del progreso en la sesión (1-10)', null=True, verbose_name='Calificación (1-10)'),
        ),
    ]
