# Generated by Django 5.2.7 on 2025-11-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('año', models.IntegerField(default=2025)),
                ('semestre', models.CharField(default='2', max_length=1)),
                ('total_estudiantes', models.IntegerField(default=0)),
                ('total_agendas_activas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticaPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(max_length=50)),
                ('año', models.IntegerField(default=2025)),
                ('semestre', models.CharField(default='2', max_length=1)),
                ('total_estudiantes', models.IntegerField(default=0)),
            ],
        ),
    ]
