# Generated by Django 5.2.7 on 2025-11-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadisticaglobal',
            options={'ordering': ['-año', '-semestre'], 'verbose_name_plural': 'Estadísticas Globales'},
        ),
        migrations.AlterModelOptions(
            name='estadisticaprograma',
            options={'ordering': ['-año', '-semestre', 'programa']},
        ),
        migrations.AddField(
            model_name='estadisticaglobal',
            name='estudiantes_graduados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticaglobal',
            name='tasa_asistencia_global',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='estadisticaglobal',
            name='total_sesiones_completadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadisticaglobal',
            name='año',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estadisticaglobal',
            name='semestre',
            field=models.CharField(choices=[('1', 'Primer Semestre'), ('2', 'Segundo Semestre')], max_length=1),
        ),
        migrations.AlterField(
            model_name='estadisticaprograma',
            name='año',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estadisticaprograma',
            name='programa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estadisticaprograma',
            name='semestre',
            field=models.CharField(choices=[('1', 'Primer Semestre'), ('2', 'Segundo Semestre')], max_length=1),
        ),
    ]
