# Generated by Django 5.2.7 on 2025-11-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0002_alter_estadisticaglobal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticaglobal',
            name='estudiantes_femeninos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticaglobal',
            name='estudiantes_ifc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticaglobal',
            name='estudiantes_masculinos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticaglobal',
            name='estudiantes_pcv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticaglobal',
            name='estudiantes_scp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticaglobal',
            name='promedio_progreso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='estadisticaprograma',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estadisticaprograma',
            name='promedio_sesiones_estudiante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='estadisticaprograma',
            name='sesiones_completadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticaprograma',
            name='sesiones_totales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadisticaprograma',
            name='tasa_completacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='estadisticaglobal',
            unique_together={('año', 'semestre')},
        ),
        migrations.AlterUniqueTogether(
            name='estadisticaprograma',
            unique_together={('programa', 'año', 'semestre')},
        ),
    ]
