# Generated by Django 5.2.7 on 2025-11-06 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEvolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(default='LA PAZ', max_length=100)),
                ('distrito_educativo', models.CharField(default='LA PAZ - 2', max_length=100)),
                ('nombre_cee', models.CharField(default='ADAPTACIÓN INFANTIL', max_length=200)),
                ('codigo_cee', models.CharField(default='80730696', max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('grado', models.CharField(blank=True, max_length=100)),
                ('codigo_rude', models.CharField(blank=True, max_length=50)),
                ('diagnostico_educativo', models.TextField(blank=True)),
                ('semestre_programa', models.CharField(default='PRIMER SEMESTRE', max_length=50)),
                ('gestion', models.CharField(default='2025', max_length=4)),
                ('desarrollo_socioemocional', models.CharField(blank=True, choices=[('no_logro', 'No Logró'), ('en_proceso', 'En Proceso'), ('si_logro', 'Si Logró')], max_length=20)),
                ('desarrollo_funciones_basicas', models.CharField(blank=True, choices=[('no_logro', 'No Logró'), ('en_proceso', 'En Proceso'), ('si_logro', 'Si Logró')], max_length=20)),
                ('desarrollo_funciones_cognitivas', models.CharField(blank=True, choices=[('no_logro', 'No Logró'), ('en_proceso', 'En Proceso'), ('si_logro', 'Si Logró')], max_length=20)),
                ('desarrollo_funciones_ejecutivas', models.CharField(blank=True, choices=[('no_logro', 'No Logró'), ('en_proceso', 'En Proceso'), ('si_logro', 'Si Logró')], max_length=20)),
                ('desarrollo_habilidades_comunicativas', models.CharField(blank=True, choices=[('no_logro', 'No Logró'), ('en_proceso', 'En Proceso'), ('si_logro', 'Si Logró')], max_length=20)),
                ('desarrollo_lectura_escritura', models.CharField(blank=True, choices=[('no_logro', 'No Logró'), ('en_proceso', 'En Proceso'), ('si_logro', 'Si Logró')], max_length=20)),
                ('desarrollo_razonamiento_matematico', models.CharField(blank=True, choices=[('no_logro', 'No Logró'), ('en_proceso', 'En Proceso'), ('si_logro', 'Si Logró')], max_length=20)),
                ('informe_progresion', models.TextField(blank=True)),
                ('otras_senales_alerta', models.TextField(blank=True)),
                ('estado_final', models.TextField(blank=True)),
                ('total_sesiones', models.IntegerField(default=0)),
                ('total_licencias', models.IntegerField(default=0)),
                ('total_faltas', models.IntegerField(default=0)),
                ('sesiones_asistidas', models.IntegerField(default=0)),
                ('recomendaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('lugar_fecha', models.CharField(default='La Paz, noviembre de 2025', max_length=100)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'Registro de Evolución',
                'verbose_name_plural': 'Registros de Evolución',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
