# Generated by Django 5.2.7 on 2025-11-06 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('registro_evolucion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDesarrollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Área de Desarrollo',
                'verbose_name_plural': 'Áreas de Desarrollo',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='InformeFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(default='LA PAZ', max_length=100)),
                ('distrito_educativo', models.CharField(default='LA PAZ - 2', max_length=100)),
                ('nombre_cee', models.CharField(default='ADAPTACIÓN INFANTIL', max_length=200)),
                ('codigo_cee', models.CharField(default='80730696', max_length=20)),
                ('codigo_edif_esc', models.CharField(default='80730433', max_length=20)),
                ('codigo_sie', models.CharField(default='80730696', max_length=20)),
                ('fundacion', models.CharField(default='6 de julio de 1966', max_length=50)),
                ('ra_numero', models.CharField(default='1753/2021', max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('grado', models.CharField(blank=True, max_length=100)),
                ('codigo_rude', models.CharField(blank=True, max_length=50)),
                ('diagnostico_educativo', models.TextField(blank=True)),
                ('semestre_programa', models.CharField(choices=[('PRIMER SEMESTRE', 'PRIMER SEMESTRE'), ('SEGUNDO SEMESTRE', 'SEGUNDO SEMESTRE')], default='PRIMER SEMESTRE', max_length=50)),
                ('gestion', models.CharField(default='2025', max_length=4)),
                ('otras_senales_alerta', models.TextField(blank=True, verbose_name='Otras Señales de Alerta')),
                ('estado_final', models.CharField(blank=True, max_length=200, verbose_name='Estado Final')),
                ('total_sesiones', models.IntegerField(default=0)),
                ('total_licencias', models.IntegerField(default=0)),
                ('total_faltas', models.IntegerField(default=0)),
                ('sesiones_asistidas', models.IntegerField(default=0)),
                ('director', models.CharField(blank=True, max_length=200, verbose_name='Director')),
                ('sello_direccion', models.BooleanField(default=False, verbose_name='Sello Dirección C.E.E.')),
                ('lugar_fecha', models.CharField(default='La Paz, noviembre de 2025', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('COMPLETADO', 'Completado'), ('APROBADO', 'Aprobado')], default='BORRADOR', max_length=20)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Docente D.A.')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_finales', to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'Informe Final',
                'verbose_name_plural': 'Informes Finales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DesarrolloEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacion', models.CharField(choices=[('NO_LOGRO', 'No Logró'), ('EN_PROCESO', 'En Proceso'), ('SI_LOGRO', 'Si Logró')], max_length=20)),
                ('recomendaciones', models.TextField(blank=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_evolucion.areadesarrollo')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desarrollos', to='registro_evolucion.informefinal')),
            ],
            options={
                'verbose_name': 'Desarrollo Educativo',
                'verbose_name_plural': 'Desarrollos Educativos',
                'unique_together': {('informe', 'area')},
            },
        ),
        migrations.DeleteModel(
            name='RegistroEvolucion',
        ),
    ]
