# Generated by Django 5.2.7 on 2025-11-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_evolucion', '0002_areadesarrollo_informefinal_desarrolloeducativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informefinal',
            name='promedio_progreso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Promedio de Progreso (0-10)'),
        ),
        migrations.AddField(
            model_name='informefinal',
            name='recomendacion_sesiones',
            field=models.CharField(blank=True, max_length=100, verbose_name='Recomendación de Sesiones'),
        ),
        migrations.AddField(
            model_name='informefinal',
            name='sesiones_evaluadas',
            field=models.IntegerField(default=0, verbose_name='Sesiones con Calificación'),
        ),
    ]
