# Generated by Django 5.2.7 on 2025-12-05 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Backup completo diciembre 2024', max_length=255, verbose_name='Nombre del Backup')),
                ('descripcion', models.TextField(blank=True, help_text='Detalles sobre lo que contiene este backup', verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='backups/%Y/%m/%d/', verbose_name='Archivo de backup')),
                ('tamano', models.BigIntegerField(default=0, verbose_name='Tamaño del archivo (bytes)')),
                ('estado', models.CharField(choices=[('completado', '✅ Completado'), ('fallido', '❌ Fallido'), ('en_progreso', '⏳ En progreso')], default='en_progreso', max_length=20, verbose_name='Estado del backup')),
                ('datos_json', models.JSONField(blank=True, default=dict, verbose_name='Datos del backup (JSON)')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó el backup')),
            ],
            options={
                'verbose_name': 'Copia de Seguridad',
                'verbose_name_plural': 'Copias de Seguridad',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['fecha_creacion'], name='backups_bac_fecha_c_f93328_idx'), models.Index(fields=['estado'], name='backups_bac_estado_98048e_idx')],
            },
        ),
    ]
