# Generated by Django 5.2.7 on 2025-11-03 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('nombres', models.CharField(max_length=150)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('zona', models.CharField(blank=True, max_length=120, null=True)),
                ('avenida', models.CharField(blank=True, max_length=120, null=True)),
                ('nro_vivienda', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('nombres', models.CharField(max_length=150)),
                ('pais', models.CharField(max_length=80)),
                ('departamento', models.CharField(max_length=80)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('edad', models.PositiveSmallIntegerField()),
                ('documento_identidad', models.CharField(max_length=20, unique=True)),
                ('codigo_rude', models.CharField(max_length=30, unique=True)),
                ('colegio_procedencia', models.CharField(blank=True, max_length=150, null=True)),
                ('nivel', models.CharField(choices=[('IFC', 'IFC'), ('PCV', 'PCV'), ('SCP', 'SCP')], max_length=3)),
                ('grado', models.CharField(choices=[('1ro', '1ro'), ('2do', '2do'), ('3ro', '3ro'), ('4to', '4to'), ('5to', '5to'), ('6to', '6to')], max_length=4)),
                ('semestre', models.CharField(choices=[('1', 'Primer Semestre'), ('2', 'Segundo Semestre')], default='1', max_length=1)),
                ('maestra_aula', models.CharField(blank=True, max_length=100, null=True)),
                ('gestion_ingreso', models.CharField(choices=[('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034')], default='2024', max_length=4)),
                ('zona', models.CharField(max_length=120)),
                ('avenida', models.CharField(blank=True, max_length=120, null=True)),
                ('nro_vivienda', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('resultados_evaluacion', models.JSONField(blank=True, default=list)),
                ('evaluacion_requerida', models.CharField(blank=True, max_length=200, null=True)),
                ('programa_apoyo', models.JSONField(blank=True, default=list)),
                ('programa_otro', models.CharField(blank=True, max_length=200, null=True)),
                ('modalidad_atencion', models.CharField(choices=[('directa', 'Atención Directa'), ('indirecta', 'Atención Indirecta')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='estudiantes.tutor')),
            ],
        ),
    ]
